PLAN_CAPABILITIES = {
    "free": {
        "risk_flags": False,
        "distribution_simulation": False,
        "mobile_warnings": False,
        "consultation": False,
        "export": False,
        "compliance_language": False,
        "readiness_verdict": False,
        "bulk_upload": False,
        "bulk_limit": 1,
    },
    "basic": {
        "risk_flags": False,
        "distribution_simulation": True,
        "mobile_warnings": False,
        "consultation": False,
        "export": False,
        "compliance_language": False,
        "readiness_verdict": True,
        "bulk_upload": False,
        "bulk_limit": 1,
    },
    "pro": {
        "risk_flags": True,
        "distribution_simulation": True,
        "mobile_warnings": True,
        "consultation": True,
        "export": True,
        "compliance_language": True,
        "readiness_verdict": True,
        "bulk_upload": True,
        "bulk_limit": 20,
    },
}
